# Generated by Django 4.2.6 on 2023-10-28 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0006_emergencyservice_service_availability"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emergencyservice",
            old_name="service_availability",
            new_name="availability",
        ),
    ]
