# Generated by Django 4.2.6 on 2023-10-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0007_rename_service_availability_emergencyservice_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyservice",
            name="description",
            field=models.TextField(default="Emergency Service"),
        ),
    ]
