# Generated by Django 4.2.6 on 2023-10-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0008_emergencyservice_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyservice",
            name="image",
            field=models.ImageField(default="No Picture", upload_to=""),
        ),
    ]
