# Generated by Django 4.2.6 on 2023-10-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0009_emergencyservice_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyservice",
            name="email",
            field=models.EmailField(default="No email", max_length=255),
        ),
    ]
