# Generated by Django 4.2.6 on 2023-11-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0011_alter_emergencyservice_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CriminalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("criminal_history", models.TextField()),
                ("image", models.ImageField(default="No Picture", upload_to="img/%y")),
            ],
        ),
        migrations.AlterField(
            model_name="emergencyservice",
            name="image",
            field=models.ImageField(default="No Picture", upload_to="img/%y"),
        ),
    ]
