# Generated by Django 4.2.6 on 2023-11-01 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0012_criminalrecord_alter_emergencyservice_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CriminalRecord",
            new_name="Criminal",
        ),
    ]
