# Generated by Django 4.2.6 on 2023-11-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0013_rename_criminalrecord_criminal"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="crime_percentage",
            field=models.FloatField(default=0),
        ),
    ]
