# Generated by Django 4.2.6 on 2023-11-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0014_location_crime_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="image",
            field=models.ImageField(default="No Picture", upload_to="img/%y"),
        ),
    ]
