# Generated by Django 4.2.6 on 2023-11-01 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0016_rename_image_location_area_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="area_image",
            new_name="image",
        ),
    ]
