# Generated by Django 4.2.6 on 2023-11-01 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0017_rename_area_image_location_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="image",
        ),
    ]
