# Generated by Django 4.2.6 on 2023-11-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0019_location_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(default="No Picture", upload_to="img/%y"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myApp.location",
            ),
        ),
    ]
