# Generated by Django 4.2.6 on 2023-11-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0020_userprofile_image_userprofile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notifications",
            field=models.ManyToManyField(
                blank=True, related_name="user_profiles", to="myApp.notification"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(default="No Picture", upload_to="img/%Y"),
        ),
    ]
