# Generated by Django 4.2.6 on 2023-11-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0022_notification_incident_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="incident_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myApp.incidentreport"
            ),
        ),
    ]
