# Generated by Django 4.2.6 on 2023-11-03 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0022_notification_incident_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
    ]
