# Generated by Django 5.0.2 on 2024-04-20 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_alter_notification_incident_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='incident_report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.incidentreport'),
        ),
    ]
