# Generated by Django 4.2.6 on 2023-11-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0024_remove_notification_incident_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="incident_report",
            field=models.ForeignKey(
                default="No Report",
                on_delete=django.db.models.deletion.CASCADE,
                to="myApp.incidentreport",
            ),
        ),
    ]
