# Generated by Django 5.0.2 on 2024-04-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_userprofile_unread_notifications_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='unread_notifications_count',
            new_name='unread_count',
        ),
    ]
